### PR TITLE
Musl inspired general fixes

### PR DESCRIPTION
**Pull request by kraj**
While compiling on mips/musl, build was failing, which highlighted some inssues under the surface.

### CODE REVIEW

**Comment by wookietreiber** [comment]
LGTM. I don't have mips/musl, so unfortunately, I can't check that it works. Would be nice if travis had this.

@vasi I'm good to merge if you are.

**Comment by vasi** [comment]
I have no idea if this will break anything on other platforms? I guess merge and see if anybody complains :P

**Comment by kraj** [comment]
I have tested it with glibc. It worked ok in my limited testing

**Comment by wookietreiber** [comment]
I have tested on my machine (x86_64) and all seems well. I have specifically tested compressing with the patch and decompressing without it.

@kraj Thanks again for the contribution.

**Pull request merged**
